# Generated by Django 4.2.11 on 2024-06-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmSerie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.CharField(default='Unavailable', max_length=5000, null=True)),
                ('datef', models.DateField(null=True)),
                ('langue', models.CharField(max_length=10, null=True)),
                ('j_aime', models.IntegerField(default=0, null=True)),
                ('j_aime_pas', models.IntegerField(default=0, null=True)),
                ('note', models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True)),
                ('poster_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('nomut', models.CharField(max_length=50)),
                ('ageut', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('genreut', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=2)),
                ('date_ut', models.DateField()),
            ],
        ),
    ]
