# Generated by Django 4.2.11 on 2024-06-16 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0002_panier_collection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'nom')},
        ),
    ]
